power: battery: remove unused sha1functionselect
../drivers/power/supply/battery_secrete/ds28e30lib/sha256_software.c:608:11: error: variable 'sha1functionselect' set but not used [-Werror,-Wunused-but-set-variable]

../drivers/power/supply/battery_secrete/ds28e30lib/ucl_sia256.c:417:8: error: variable 'sha1functionselect' set but not used [-Werror,-Wunused-but-set-variable]

clang stops on -Wunused-but-set-variable.  sha1functionselect
was left behind after the DS28E30 SHA-1 helper was removed; nothing
reads it. Keep with `__maybe_unused` directive

(cherry picked from commit 509426b3e224fff779e7aca4c100ba0cc59f99fb)
(cherry picked from commit 3f3a8171173f6ba0f9399836bbe2a7749920af3d)