power: charger: function definition without prototype
../drivers/power/supply/wt_charger/wt_chg.c:173:25: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]

(cherry picked from commit cb451d7363d2dae45d6021a386c2449afce23328)
(cherry picked from commit c8091049f000b30db6b55009bd8afc16222beafe)