techpack: audio: Fix strict-prototypes errors
../techpack/audio/asoc/codecs/fs19xx/fsm_i2c.c:39:20: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]

(cherry picked from commit 9bf99089bb1ba74c287a7ea32a053586215a1db6)
(cherry picked from commit fc0d65ff4937a73cdb50b188767a5a6371ce6c86)