qseecom: Fix -Wpointer-to-int-cast
drivers/misc/qseecom.c:3723:28: error: cast to smaller integer type 'uint32_t' (aka 'unsigned int') from 'void *' [-Werror,-Wvoid-pointer-to-int-cast]
                        send_data_req.req_ptr = (uint32_t)req->cmd_req_buf;
                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/misc/qseecom.c:3724:28: error: cast to smaller integer type 'uint32_t' (aka 'unsigned int') from 'void *' [-Werror,-Wvoid-pointer-to-int-cast]
                        send_data_req.rsp_ptr = (uint32_t)req->resp_buf;
                                                ^~~~~~~~~~~~~~~~~~~~~~~

Fix `send_data_req.rsp_ptr = (uint32_t)req->resp_buf;` by casting
pointer value into uintptr_t, then compiler assignment will truncate to 32bit
to fit `uint32_t send_data_req.rsp_ptr` later.

Bug: 171827315
Signed-off-by: lucaswei <lucaswei@google.com>
Change-Id: I0643c4a556d933293715c7ef7727148d0fb59c25
(cherry picked from commit 663d6ec3416b3b5ec6b4e5c0ca0a7e669e076efb)
(cherry picked from commit 3a0d09032ecc7444e0f2f81d59d929e583bac182)
(cherry picked from commit 2426fe84b11dff6e31936da0afa5553636ebde54)
(cherry picked from commit 6e02646b4235e590718ec3b46d5b5c7a2aac6ac8)