mm/zsmalloc: add missing prototype to try_schedule_zs_compact
Addresses
'../mm/zsmalloc.c:2430:29: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]\n' b' 2430 | void try_schedule_zs_compact()

Clang treats functions declared without an explicit parameter list as “old-style C”, which is deprecated; adding an explicit void parameter fixes it

(cherry picked from commit f86064e1df9d4ad4625c6cc8520619eb7b32c9dc)
(cherry picked from commit 72a70858964e6cc96e511379583f480ba2b91145)