disp: msm: sde: Fix strict-prototypes error
"../techpack/display/msm/sde/sde_hw_dsc_1_2.c:80:15: error: type specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]\n" b'   80 | static inline _dsc_subblk_offset(struct sde_hw_dsc *hw_dsc, int s_id,\n' b'      | ~~~~~~~~~~~~~ ^\n' b'

Change-Id: I2c6d8f58782ee52225916bf10b572bb08054f443
(cherry picked from commit 729a124d6788ec51b4061bc6dafe4b1ed04acdd8)
(cherry picked from commit 6a5455fb22544cfec90453bdc941392880642a68)
(cherry picked from commit 7f99a1c358344f265fe1930cd2eafa32300fff88)
(cherry picked from commit 7a28de1a52d2ecda66f139c462c242570681b2f0)