techpack: cam: Fix strict-prototypes errors
../techpack/camera/drivers/cam_utils/cam_debug_util.c:22:59: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]

(cherry picked from commit 1edf87e1e56c4a9e23562e69017464ce1c2a3c29)