leds: qpnp-flash-v2: Fix compilation error
Fix a compilation error seen when casting void pointer to
int by casting it to uintptr_t instead.

../drivers/leds/leds-qpnp-flash-v2.c:2973:19: warning: cast to smaller integer type 'u8' (aka 'unsigned char') from 'const void *' [-Wvoid-pointer-to-int-cast]\n" error, forbidden warning: leds-qpnp-flash-v2.c:2973

Change-Id: I679da04f21041c386fa7ad8905ede94e12ea160c
Signed-off-by: Jishnu Prakash <quic_jprakash@quicinc.com>
(cherry picked from commit d951baf7d23a846e803864af94455fbaca5abb90)