techpack: camera: Fix enum comparison warning
drivers/cam_isp/isp_hw_mgr/cam_tfe_hw_mgr.c:3038:21: error:
comparison of different enumeration types ('enum cam_tfe_csid_halt_cmd'
and 'enum cam_ife_csid_halt_cmd') [-Werror,-Wenum-compare]

	if (csid_halt_type == CAM_CSID_HALT_IMMEDIATELY)
	    ~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~

Change-Id: I13b0c86ded5ba544380c2ca9fd3d1a73db9ea63b
(cherry picked from commit f17b926e06dcbee1b3710b7bcef50956a8bb6bff)
(cherry picked from commit 5150700c07cd67ba3c19d5c7a5c414dd5a4bf264)