techpack: asoc: Fix strict-prototypes errors
../techpack/audio/asoc/holi.c:768:38: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]\n' b'  768 | static void msm_audio_add_qos_request()

../techpack/audio/asoc/holi.c:797:41: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]\n' b'  797 | static void msm_audio_remove_qos_request()

(cherry picked from commit 94ddfdb0939ff76e6eff350266a8a1ee8ad94e86)
(cherry picked from commit 38dff3e23ef7a3c6091144ae96c7bcfff87332da)
(cherry picked from commit f389a797646e9aae08782f43b5ef8fb6706147c3)
(cherry picked from commit 8e96da1775acbcd742634b890a91089a8dc3a839)