drivers: power: fix -Wunused-but-set-variable errors
../drivers/power/supply/battery_secrete/auth_battery.c:815:6: error: variable 'ret' set but not used [-Werror,-Wunused-but-set-variable]

../drivers/power/supply/battery_secrete/ds28e30.c:2428:6: error: variable 'ret' set but not used [-Werror,-Wunused-but-set-variable]

The local variable “ret” is written but never read, triggering -Werror,-Wunused-but-set param

(cherry picked from commit bc703319cf664ebe9b6f9430d95e56336e6ee899)
(cherry picked from commit fbe4d43f09c0c528d9410e91522341da7baeb7f3)