power: smb5: Fix -Wpointer-to-int-cast.
Fixes:
drivers/power/supply/qcom/qpnp-smb5.c:338:16: error: cast to smaller
    integer type 'u8' (aka 'unsigned char') from 'const void *'
    [-Werror,-Wvoid-pointer-to-int-cast]
        int subtype = (u8)of_device_get_match_data(chg->dev);
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Change-Id: I30d500db49c4aae95efe7d41c88b04da3468fa29
(cherry picked from commit 14b1901120532105735180ee3f038b2557a6b40f)
(cherry picked from commit 1109f08cdd6e4c0cd790c00d2cc1958041a6594d)