usb: typec: Fix strict-prototypes error
../drivers/usb/typec/P86801_tcpc/rt_pd_manager.c:260:25: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]

(cherry picked from commit edebb823895bb9d95dffce16c60ef9f3682ae08b)